[package]
name = "gogoanime-scraper"
version = "1.2.4"
edition = "2021"
description = "A blazing fast anime scraper for GoGoAnime"
license = "MIT"
repository = "https://github.com/zerodev-exe/gogoanime-scraper"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["cookies", "blocking", "json"] }
colored = "2.2.0"
chrono = "0.4.39"
indicatif = "0.18.4"
async-trait = "0.1.85"
futures = "0.3.30"
dirs = "6.0.0"
serde_json = "1.0.135"

[lib]
name = "gogoanime_scraper"
path = "src/lib.rs"

[[bin]]
name = "anidl"
path = "src/main.rs"
